<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_v1.proto

namespace App\Grpc\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth.v1.LiveResponse</code>
 */
class LiveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool alive = 1;</code>
     */
    protected $alive = false;
    /**
     * Generated from protobuf field <code>string timestamp = 2;</code>
     */
    protected $timestamp = '';
    /**
     * Generated from protobuf field <code>double uptime = 3;</code>
     */
    protected $uptime = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $alive
     *     @type string $timestamp
     *     @type float $uptime
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\AuthV1\AuthV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool alive = 1;</code>
     * @return bool
     */
    public function getAlive()
    {
        return $this->alive;
    }

    /**
     * Generated from protobuf field <code>bool alive = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlive($var)
    {
        GPBUtil::checkBool($var);
        $this->alive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 2;</code>
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double uptime = 3;</code>
     * @return float
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    /**
     * Generated from protobuf field <code>double uptime = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkDouble($var);
        $this->uptime = $var;

        return $this;
    }

}

