<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_v1.proto

namespace App\Grpc\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth.v1.LoginRequest</code>
 */
class LoginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string username = 1;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string password = 2;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string appVersion = 3;</code>
     */
    protected $appVersion = '';
    /**
     * Generated from protobuf field <code>string passwordEncoding = 4;</code>
     */
    protected $passwordEncoding = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $username
     *     @type string $password
     *     @type string $appVersion
     *     @type string $passwordEncoding
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\AuthV1\AuthV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string appVersion = 3;</code>
     * @return string
     */
    public function getAppVersion()
    {
        return $this->appVersion;
    }

    /**
     * Generated from protobuf field <code>string appVersion = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAppVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->appVersion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string passwordEncoding = 4;</code>
     * @return string
     */
    public function getPasswordEncoding()
    {
        return $this->passwordEncoding;
    }

    /**
     * Generated from protobuf field <code>string passwordEncoding = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPasswordEncoding($var)
    {
        GPBUtil::checkString($var, True);
        $this->passwordEncoding = $var;

        return $this;
    }

}

