<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_v1.proto

namespace App\Grpc\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth.v1.LoginResponse</code>
 */
class LoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string accessToken = 1;</code>
     */
    protected $accessToken = '';
    /**
     * Generated from protobuf field <code>string refreshToken = 2;</code>
     */
    protected $refreshToken = '';
    /**
     * Generated from protobuf field <code>bool mfaRequired = 3;</code>
     */
    protected $mfaRequired = false;
    /**
     * Generated from protobuf field <code>bool requiresAppUpdate = 4;</code>
     */
    protected $requiresAppUpdate = false;
    /**
     * Generated from protobuf field <code>string tokenType = 5;</code>
     */
    protected $tokenType = '';
    /**
     * Generated from protobuf field <code>int32 expiresIn = 6;</code>
     */
    protected $expiresIn = 0;
    /**
     * Generated from protobuf field <code>string sessionId = 7;</code>
     */
    protected $sessionId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $accessToken
     *     @type string $refreshToken
     *     @type bool $mfaRequired
     *     @type bool $requiresAppUpdate
     *     @type string $tokenType
     *     @type int $expiresIn
     *     @type string $sessionId
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\AuthV1\AuthV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string accessToken = 1;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->accessToken;
    }

    /**
     * Generated from protobuf field <code>string accessToken = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->accessToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string refreshToken = 2;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->refreshToken;
    }

    /**
     * Generated from protobuf field <code>string refreshToken = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->refreshToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool mfaRequired = 3;</code>
     * @return bool
     */
    public function getMfaRequired()
    {
        return $this->mfaRequired;
    }

    /**
     * Generated from protobuf field <code>bool mfaRequired = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setMfaRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->mfaRequired = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool requiresAppUpdate = 4;</code>
     * @return bool
     */
    public function getRequiresAppUpdate()
    {
        return $this->requiresAppUpdate;
    }

    /**
     * Generated from protobuf field <code>bool requiresAppUpdate = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequiresAppUpdate($var)
    {
        GPBUtil::checkBool($var);
        $this->requiresAppUpdate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tokenType = 5;</code>
     * @return string
     */
    public function getTokenType()
    {
        return $this->tokenType;
    }

    /**
     * Generated from protobuf field <code>string tokenType = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenType($var)
    {
        GPBUtil::checkString($var, True);
        $this->tokenType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 expiresIn = 6;</code>
     * @return int
     */
    public function getExpiresIn()
    {
        return $this->expiresIn;
    }

    /**
     * Generated from protobuf field <code>int32 expiresIn = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setExpiresIn($var)
    {
        GPBUtil::checkInt32($var);
        $this->expiresIn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sessionId = 7;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->sessionId;
    }

    /**
     * Generated from protobuf field <code>string sessionId = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionId = $var;

        return $this;
    }

}

