<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_v1.proto

namespace App\Grpc\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth.v1.Empty</code>
 */
class PBEmpty extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\AuthV1\AuthV1::initOnce();
        parent::__construct($data);
    }

}

