<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_v1.proto

namespace App\Grpc\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth.v1.WhitelistResponse</code>
 */
class WhitelistResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string routes = 1;</code>
     */
    private $routes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $routes
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\AuthV1\AuthV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string routes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoutes()
    {
        return $this->routes;
    }

    /**
     * Generated from protobuf field <code>repeated string routes = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoutes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->routes = $arr;

        return $this;
    }

}

