<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notificaciones_v1.proto

namespace App\Grpc\Notificaciones\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notificaciones.v1.CreateNotificationRequest</code>
 */
class CreateNotificationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string usuarioId = 1;</code>
     */
    protected $usuarioId = '';
    /**
     * Generated from protobuf field <code>string email = 2;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string identificacion = 3;</code>
     */
    protected $identificacion = '';
    /**
     * Generated from protobuf field <code>string titulo = 4;</code>
     */
    protected $titulo = '';
    /**
     * Generated from protobuf field <code>string mensaje = 5;</code>
     */
    protected $mensaje = '';
    /**
     * Generated from protobuf field <code>string tipo = 6;</code>
     */
    protected $tipo = '';
    /**
     * Generated from protobuf field <code>string canal = 7;</code>
     */
    protected $canal = '';
    /**
     * Generated from protobuf field <code>string prioridad = 8;</code>
     */
    protected $prioridad = '';
    /**
     * Generated from protobuf field <code>string iconId = 9;</code>
     */
    protected $iconId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $usuarioId
     *     @type string $email
     *     @type string $identificacion
     *     @type string $titulo
     *     @type string $mensaje
     *     @type string $tipo
     *     @type string $canal
     *     @type string $prioridad
     *     @type string $iconId
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\NotificacionesV1\NotificacionesV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 1;</code>
     * @return string
     */
    public function getUsuarioId()
    {
        return $this->usuarioId;
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsuarioId($var)
    {
        GPBUtil::checkString($var, True);
        $this->usuarioId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 2;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identificacion = 3;</code>
     * @return string
     */
    public function getIdentificacion()
    {
        return $this->identificacion;
    }

    /**
     * Generated from protobuf field <code>string identificacion = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentificacion($var)
    {
        GPBUtil::checkString($var, True);
        $this->identificacion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string titulo = 4;</code>
     * @return string
     */
    public function getTitulo()
    {
        return $this->titulo;
    }

    /**
     * Generated from protobuf field <code>string titulo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTitulo($var)
    {
        GPBUtil::checkString($var, True);
        $this->titulo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mensaje = 5;</code>
     * @return string
     */
    public function getMensaje()
    {
        return $this->mensaje;
    }

    /**
     * Generated from protobuf field <code>string mensaje = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMensaje($var)
    {
        GPBUtil::checkString($var, True);
        $this->mensaje = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tipo = 6;</code>
     * @return string
     */
    public function getTipo()
    {
        return $this->tipo;
    }

    /**
     * Generated from protobuf field <code>string tipo = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTipo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tipo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string canal = 7;</code>
     * @return string
     */
    public function getCanal()
    {
        return $this->canal;
    }

    /**
     * Generated from protobuf field <code>string canal = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCanal($var)
    {
        GPBUtil::checkString($var, True);
        $this->canal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prioridad = 8;</code>
     * @return string
     */
    public function getPrioridad()
    {
        return $this->prioridad;
    }

    /**
     * Generated from protobuf field <code>string prioridad = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPrioridad($var)
    {
        GPBUtil::checkString($var, True);
        $this->prioridad = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string iconId = 9;</code>
     * @return string
     */
    public function getIconId()
    {
        return $this->iconId;
    }

    /**
     * Generated from protobuf field <code>string iconId = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setIconId($var)
    {
        GPBUtil::checkString($var, True);
        $this->iconId = $var;

        return $this;
    }

}

