<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notificaciones_v1.proto

namespace App\Grpc\Notificaciones\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notificaciones.v1.ListNotificationsResponse</code>
 */
class ListNotificationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .notificaciones.v1.Notification notifications = 1;</code>
     */
    private $notifications;
    /**
     * Generated from protobuf field <code>int32 unreadCount = 2;</code>
     */
    protected $unreadCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\App\Grpc\Notificaciones\V1\Notification>|\Google\Protobuf\Internal\RepeatedField $notifications
     *     @type int $unreadCount
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\NotificacionesV1\NotificacionesV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .notificaciones.v1.Notification notifications = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotifications()
    {
        return $this->notifications;
    }

    /**
     * Generated from protobuf field <code>repeated .notificaciones.v1.Notification notifications = 1;</code>
     * @param array<\App\Grpc\Notificaciones\V1\Notification>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotifications($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Grpc\Notificaciones\V1\Notification::class);
        $this->notifications = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unreadCount = 2;</code>
     * @return int
     */
    public function getUnreadCount()
    {
        return $this->unreadCount;
    }

    /**
     * Generated from protobuf field <code>int32 unreadCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUnreadCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->unreadCount = $var;

        return $this;
    }

}

