<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notificaciones_v1.proto

namespace App\Grpc\Notificaciones\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notificaciones.v1.ListNotificationsRequest</code>
 */
class ListNotificationsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string usuarioId = 1;</code>
     */
    protected $usuarioId = '';
    /**
     * Generated from protobuf field <code>string estado = 2;</code>
     */
    protected $estado = '';
    /**
     * Generated from protobuf field <code>int32 limit = 3;</code>
     */
    protected $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $usuarioId
     *     @type string $estado
     *     @type int $limit
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\NotificacionesV1\NotificacionesV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 1;</code>
     * @return string
     */
    public function getUsuarioId()
    {
        return $this->usuarioId;
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsuarioId($var)
    {
        GPBUtil::checkString($var, True);
        $this->usuarioId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string estado = 2;</code>
     * @return string
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * Generated from protobuf field <code>string estado = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEstado($var)
    {
        GPBUtil::checkString($var, True);
        $this->estado = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 3;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

