<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notificaciones_v1.proto

namespace App\Grpc\Notificaciones\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notificaciones.v1.MarkReadRequest</code>
 */
class MarkReadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string usuarioId = 2;</code>
     */
    protected $usuarioId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $usuarioId
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\NotificacionesV1\NotificacionesV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 2;</code>
     * @return string
     */
    public function getUsuarioId()
    {
        return $this->usuarioId;
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsuarioId($var)
    {
        GPBUtil::checkString($var, True);
        $this->usuarioId = $var;

        return $this;
    }

}

