<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notificaciones_v1.proto

namespace App\Grpc\Notificaciones\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notificaciones.v1.Notification</code>
 */
class Notification extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string usuarioId = 2;</code>
     */
    protected $usuarioId = '';
    /**
     * Generated from protobuf field <code>string titulo = 3;</code>
     */
    protected $titulo = '';
    /**
     * Generated from protobuf field <code>string mensaje = 4;</code>
     */
    protected $mensaje = '';
    /**
     * Generated from protobuf field <code>string tipo = 5;</code>
     */
    protected $tipo = '';
    /**
     * Generated from protobuf field <code>string canal = 6;</code>
     */
    protected $canal = '';
    /**
     * Generated from protobuf field <code>string prioridad = 7;</code>
     */
    protected $prioridad = '';
    /**
     * Generated from protobuf field <code>string estado = 8;</code>
     */
    protected $estado = '';
    /**
     * Generated from protobuf field <code>bool leida = 9;</code>
     */
    protected $leida = false;
    /**
     * Generated from protobuf field <code>string iconId = 10;</code>
     */
    protected $iconId = '';
    /**
     * Generated from protobuf field <code>string creadoEn = 11;</code>
     */
    protected $creadoEn = '';
    /**
     * Generated from protobuf field <code>string leidoEn = 12;</code>
     */
    protected $leidoEn = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $usuarioId
     *     @type string $titulo
     *     @type string $mensaje
     *     @type string $tipo
     *     @type string $canal
     *     @type string $prioridad
     *     @type string $estado
     *     @type bool $leida
     *     @type string $iconId
     *     @type string $creadoEn
     *     @type string $leidoEn
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\NotificacionesV1\NotificacionesV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 2;</code>
     * @return string
     */
    public function getUsuarioId()
    {
        return $this->usuarioId;
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsuarioId($var)
    {
        GPBUtil::checkString($var, True);
        $this->usuarioId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string titulo = 3;</code>
     * @return string
     */
    public function getTitulo()
    {
        return $this->titulo;
    }

    /**
     * Generated from protobuf field <code>string titulo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTitulo($var)
    {
        GPBUtil::checkString($var, True);
        $this->titulo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mensaje = 4;</code>
     * @return string
     */
    public function getMensaje()
    {
        return $this->mensaje;
    }

    /**
     * Generated from protobuf field <code>string mensaje = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMensaje($var)
    {
        GPBUtil::checkString($var, True);
        $this->mensaje = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tipo = 5;</code>
     * @return string
     */
    public function getTipo()
    {
        return $this->tipo;
    }

    /**
     * Generated from protobuf field <code>string tipo = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTipo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tipo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string canal = 6;</code>
     * @return string
     */
    public function getCanal()
    {
        return $this->canal;
    }

    /**
     * Generated from protobuf field <code>string canal = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCanal($var)
    {
        GPBUtil::checkString($var, True);
        $this->canal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prioridad = 7;</code>
     * @return string
     */
    public function getPrioridad()
    {
        return $this->prioridad;
    }

    /**
     * Generated from protobuf field <code>string prioridad = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPrioridad($var)
    {
        GPBUtil::checkString($var, True);
        $this->prioridad = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string estado = 8;</code>
     * @return string
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * Generated from protobuf field <code>string estado = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEstado($var)
    {
        GPBUtil::checkString($var, True);
        $this->estado = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool leida = 9;</code>
     * @return bool
     */
    public function getLeida()
    {
        return $this->leida;
    }

    /**
     * Generated from protobuf field <code>bool leida = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setLeida($var)
    {
        GPBUtil::checkBool($var);
        $this->leida = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string iconId = 10;</code>
     * @return string
     */
    public function getIconId()
    {
        return $this->iconId;
    }

    /**
     * Generated from protobuf field <code>string iconId = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setIconId($var)
    {
        GPBUtil::checkString($var, True);
        $this->iconId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string creadoEn = 11;</code>
     * @return string
     */
    public function getCreadoEn()
    {
        return $this->creadoEn;
    }

    /**
     * Generated from protobuf field <code>string creadoEn = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCreadoEn($var)
    {
        GPBUtil::checkString($var, True);
        $this->creadoEn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string leidoEn = 12;</code>
     * @return string
     */
    public function getLeidoEn()
    {
        return $this->leidoEn;
    }

    /**
     * Generated from protobuf field <code>string leidoEn = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setLeidoEn($var)
    {
        GPBUtil::checkString($var, True);
        $this->leidoEn = $var;

        return $this;
    }

}

