<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notificaciones_v1.proto

namespace App\Grpc\Notificaciones\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notificaciones.v1.NotificationResponse</code>
 */
class NotificationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>.notificaciones.v1.Notification notification = 2;</code>
     */
    protected $notification = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type \App\Grpc\Notificaciones\V1\Notification $notification
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\NotificacionesV1\NotificacionesV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.notificaciones.v1.Notification notification = 2;</code>
     * @return \App\Grpc\Notificaciones\V1\Notification|null
     */
    public function getNotification()
    {
        return $this->notification;
    }

    public function hasNotification()
    {
        return isset($this->notification);
    }

    public function clearNotification()
    {
        unset($this->notification);
    }

    /**
     * Generated from protobuf field <code>.notificaciones.v1.Notification notification = 2;</code>
     * @param \App\Grpc\Notificaciones\V1\Notification $var
     * @return $this
     */
    public function setNotification($var)
    {
        GPBUtil::checkMessage($var, \App\Grpc\Notificaciones\V1\Notification::class);
        $this->notification = $var;

        return $this;
    }

}

