<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notificaciones_v1.proto

namespace App\Grpc\Notificaciones\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>notificaciones.v1.SendEmailRequest</code>
 */
class SendEmailRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string usuarioId = 1;</code>
     */
    protected $usuarioId = '';
    /**
     * Generated from protobuf field <code>string toEmail = 2;</code>
     */
    protected $toEmail = '';
    /**
     * Generated from protobuf field <code>string toName = 3;</code>
     */
    protected $toName = '';
    /**
     * Generated from protobuf field <code>string subject = 4;</code>
     */
    protected $subject = '';
    /**
     * Generated from protobuf field <code>string plainText = 5;</code>
     */
    protected $plainText = '';
    /**
     * Generated from protobuf field <code>string html = 6;</code>
     */
    protected $html = '';
    /**
     * Generated from protobuf field <code>string tipo = 7;</code>
     */
    protected $tipo = '';
    /**
     * Generated from protobuf field <code>string prioridad = 8;</code>
     */
    protected $prioridad = '';
    /**
     * Generated from protobuf field <code>string source = 9;</code>
     */
    protected $source = '';
    /**
     * Generated from protobuf field <code>repeated .notificaciones.v1.EmailMetadata metadata = 10;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $usuarioId
     *     @type string $toEmail
     *     @type string $toName
     *     @type string $subject
     *     @type string $plainText
     *     @type string $html
     *     @type string $tipo
     *     @type string $prioridad
     *     @type string $source
     *     @type array<\App\Grpc\Notificaciones\V1\EmailMetadata>|\Google\Protobuf\Internal\RepeatedField $metadata
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\NotificacionesV1\NotificacionesV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 1;</code>
     * @return string
     */
    public function getUsuarioId()
    {
        return $this->usuarioId;
    }

    /**
     * Generated from protobuf field <code>string usuarioId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsuarioId($var)
    {
        GPBUtil::checkString($var, True);
        $this->usuarioId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string toEmail = 2;</code>
     * @return string
     */
    public function getToEmail()
    {
        return $this->toEmail;
    }

    /**
     * Generated from protobuf field <code>string toEmail = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->toEmail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string toName = 3;</code>
     * @return string
     */
    public function getToName()
    {
        return $this->toName;
    }

    /**
     * Generated from protobuf field <code>string toName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setToName($var)
    {
        GPBUtil::checkString($var, True);
        $this->toName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject = 4;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Generated from protobuf field <code>string subject = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plainText = 5;</code>
     * @return string
     */
    public function getPlainText()
    {
        return $this->plainText;
    }

    /**
     * Generated from protobuf field <code>string plainText = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPlainText($var)
    {
        GPBUtil::checkString($var, True);
        $this->plainText = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string html = 6;</code>
     * @return string
     */
    public function getHtml()
    {
        return $this->html;
    }

    /**
     * Generated from protobuf field <code>string html = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setHtml($var)
    {
        GPBUtil::checkString($var, True);
        $this->html = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tipo = 7;</code>
     * @return string
     */
    public function getTipo()
    {
        return $this->tipo;
    }

    /**
     * Generated from protobuf field <code>string tipo = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTipo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tipo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prioridad = 8;</code>
     * @return string
     */
    public function getPrioridad()
    {
        return $this->prioridad;
    }

    /**
     * Generated from protobuf field <code>string prioridad = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPrioridad($var)
    {
        GPBUtil::checkString($var, True);
        $this->prioridad = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source = 9;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>string source = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .notificaciones.v1.EmailMetadata metadata = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>repeated .notificaciones.v1.EmailMetadata metadata = 10;</code>
     * @param array<\App\Grpc\Notificaciones\V1\EmailMetadata>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Grpc\Notificaciones\V1\EmailMetadata::class);
        $this->metadata = $arr;

        return $this;
    }

}

